version: '3'
services:
  php:
    build: ./docker/php
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysql-data:/var/lib/mysql
    # ports: 
    # - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=myuser
      - PMA_PASSWORD=mypassword
    depends_on:
      - mysql

volumes:
  mysql-data: