version: '3'

services:
  php:
    build: ./docker/php
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./app:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=myuser
      - PMA_PASSWORD=mypassword
    depends_on:
      - database


volumes:
  database-data: